version: '3.7'
services: 
  vcenter:
    image: 'vcenter:1.0'
    build: .
    ports:
      - '8443:8443'
    restart: 'always'
    environment: 
      - 'GOPATH=/app'
      - 'GOVC_URL=localhost:8443'
      - 'GOVC_USERNAME=user'
      - 'GOVC_PASSWORD=pass'
      - 'GOVC_INSECURE=true'
    command: '/app/bin/vcsim -l 0.0.0.0:8443'
    container_name: 'vcenter'